In [1]:
""" Example using approach_2"""

' Example using approach_2'

In [1]:
import numpy as np
from path_prob import generate_points
from approach_2 import sorted_path
import matplotlib.pylab as plt

In [4]:
grid1 = generate_points(100)
sort1 = sorted_path(grid1, axes=[1,0], direction=1)

0 - 1
1 - 1


In [5]:
plt.plot(grid1[:,0], grid1[:,1], 'o')
plt.plot(sort1[:,0], sort1[:,1], '-')
plt.show()

In [4]:
sort1

[array([ 0.89903719,  0.00901158]),
 array([ 0.35723894,  0.00914968]),
 array([ 0.45512919,  0.05228408]),
 array([ 0.37587909,  0.06188013]),
 array([ 0.36397688,  0.06899157]),
 array([ 0.91102428,  0.06939857]),
 array([ 0.80922487,  0.07059151]),
 array([ 0.93002835,  0.07188632]),
 array([ 0.22754195,  0.07724944]),
 array([ 0.16990181,  0.11996756]),
 array([ 0.72333699,  0.12510078]),
 array([ 0.54020877,  0.14255318]),
 array([ 0.69185091,  0.14335315]),
 array([ 0.88605658,  0.14446582]),
 array([ 0.96436785,  0.14816945]),
 array([ 0.02514723,  0.15517697]),
 array([ 0.20672098,  0.15652735]),
 array([ 0.71658686,  0.16393526]),
 array([ 0.06702434,  0.17002431]),
 array([ 0.35805022,  0.17281465]),
 array([ 0.58791248,  0.17945762]),
 array([ 0.76977613,  0.20889994]),
 array([ 0.19431786,  0.21242349]),
 array([ 0.39563148,  0.22444726]),
 array([ 0.60704982,  0.22638822]),
 array([ 0.85214408,  0.22907286]),
 array([ 0.75758184,  0.23061575]),
 array([ 0.8820219 ,  0.2308

In [5]:
sort2 = np.array(sort1)

In [6]:
sort2

array([[ 0.89903719,  0.00901158],
       [ 0.35723894,  0.00914968],
       [ 0.45512919,  0.05228408],
       [ 0.37587909,  0.06188013],
       [ 0.36397688,  0.06899157],
       [ 0.91102428,  0.06939857],
       [ 0.80922487,  0.07059151],
       [ 0.93002835,  0.07188632],
       [ 0.22754195,  0.07724944],
       [ 0.16990181,  0.11996756],
       [ 0.72333699,  0.12510078],
       [ 0.54020877,  0.14255318],
       [ 0.69185091,  0.14335315],
       [ 0.88605658,  0.14446582],
       [ 0.96436785,  0.14816945],
       [ 0.02514723,  0.15517697],
       [ 0.20672098,  0.15652735],
       [ 0.71658686,  0.16393526],
       [ 0.06702434,  0.17002431],
       [ 0.35805022,  0.17281465],
       [ 0.58791248,  0.17945762],
       [ 0.76977613,  0.20889994],
       [ 0.19431786,  0.21242349],
       [ 0.39563148,  0.22444726],
       [ 0.60704982,  0.22638822],
       [ 0.85214408,  0.22907286],
       [ 0.75758184,  0.23061575],
       [ 0.8820219 ,  0.23085931],
       [ 0.36822165,